title: Apache Drill - Schema-free SQL for Hadoop, NoSQL and Cloud Storage
title_suffix: Apache Drill # This is appended to every page title on the site

email: dzamo@apache.org
permalink: pretty

description: > # this means to ignore newlines until "baseurl:"
  The official user documentation for Apache Drill.

baseurl: "/drill" # Base URL when hosted on GitHub Pages (drill repository under apache account)
noindex: 1

# Uncomment to use the redcarpet Markdown processor (not supported by GH Pages) instead of Kramdown
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

collections:
  docs:
    output: true
    permalink: /docs/:slug/

defaults:
  - scope:
      type: docs # This defines the default for anything in the docs collection. An alternative would be to use "path: _docs" here.
    values:
      layout: docpage

sass:
  style: :compressed

plugins:
  - jekyll-redirect-from
