title: Apache Drill - Schema-free SQL for Hadoop, NoSQL and Cloud Storage
title_suffix: Apache Drill # This is appended to every page title on the site

email: tshiran@apache.org
permalink: pretty

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/drill" # Base URL when hosted on GitHub Pages (drill repository under apache account)
noindex: 1
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

collections:
  docs:
    output: true
    permalink: /docs/:title/

defaults:
  -
    scope:
      type: docs # This defines the default for anything in the docs collection. An alternative would be to use "path: _docs" here.
    values:
      layout: docpage

sass:
  style: :compressed

gems:
  - jekyll-redirect-from
